### PR TITLE
- Added OnPrintToChat(BasePlayer player, string format, object[] args)

### PR DESCRIPTION
**Pull request by mbedda**
Added OnPrintToChat(string format, object[] args) & OnPrintToChat(BasePlayer player, string format, object[] args)

### CODE REVIEW

**Comment by MrBlue** [comment]
Hey, what's the reason for those hooks being added? Can't you use the `OnSendCommand` and `OnBroadcastCommand` hooks for this already?

**Comment by mbedda** [comment]
`OnSendCommand` and `OnBroadcastCommand` do not intercept messages, which if they did they would cover all chat messages as most call `BasePlayer.SendConsoleCommand`. 

An example of this being used is this https://codefling.com/plugins/chat-to-notifications, were I convert some chat messages to notification to clear plugins chat spam. Here i had to use Harmony to intercept at `SendConsoleCommand` and `PrintToChat`, doing that for `ConsoleNetwork` functions was not great performance wise as it handles all commands (not only "chat.add" & "chat.add2" "say"..)

**Comment by MrBlue** [comment]
Both `PrintToChat` methods call either `OnSendCommand` or `OnBroadcastCommand` internally so it would intercept any message being sent using the `PrintToChat` message?

**Comment by mbedda** [comment]
Intercept meaning they do not override default behavior

**Comment by MrBlue** [comment]
Okay so what you're saying is we should make the `OnSendCommand` and `OnBroadcastCommand` have a return behavior?

**Comment by mbedda** [comment]
yes exactly

**Comment by MrBlue** [comment]
Both OnSendCommand hooks and the OnBroadcastCommand hooks will now cancel when returning a non null value

**Pull request closed without merging**
