### PR TITLE
Add Patches to CombatLog.Log

### PR DESCRIPTION
**Pull request by dassjosh**
- Add Patches to CombatLog.Log due to recent changes not correctly checking unity game object for null causing RPC Error in OnProjectileAttack

### CODE REVIEW

**Comment by WheteThunger** [comment]
When are people encountering the `RPC error in OnProjectileAttack`? In conjunction with plugins that are deleting the held entity while a projectile is in flight, or in vanilla cases as well?

**Comment by dassjosh** [comment]
This has been confirmed to be a modded issue. Instead of trying to update all plugins that have this issue figured it would be easier to just patch in the correct checks.

**Comment by shaitobu** [comment]
> 

or if player dies/disconnects while projectile is in flight

**Comment by MrBlue** [comment]
This will be fixed by Facepunch next update! (Thanks @Jake-Rich!)

**Pull request closed without merging**
