### PR TITLE
Add hook handle unknown chat command

### PR DESCRIPTION
**Pull request by rostov114**
To create dynamic unregistered chat commands.

### CODE REVIEW

**Comment by MrBlue** [comment]
What's the exact use-case of this hook?

**Comment by rostov114** [comment]
1. Player create string data (example: `/create test`), save in data file 
2. Player(s) using in chat command: `/test`

**Comment by MrBlue** [comment]
You can already dynamically register commands and there are already plugins like https://umod.org/plugins/custom-chat-commands that do this, I don't see a reason for this hook to exist...

**Comment by austinv900** [comment]
@MrBlue someone in discord also wanted the ability to log any command even nonexistent ones. Oxide doesn't really allow that right now.

**Comment by MrBlue** [comment]
> 

The OnPlayerCommand hook gets called before any command handling is done. So you should be able to use that to run any command ran by players, even nonexistent ones.

**Comment by rostov114** [comment]
> The OnPlayerCommand hook gets called before any command handling is done. So you should be able to use that to run any command ran by players, even nonexistent ones.

Sometimes it is necessary to intercept processing in this place. 
**OnPlayerCommand** - low performance, because it registers for any command call.

**Pull request closed without merging**
