### PR TITLE
Added OnPlayerEnsureUpdated Hook

### PR DESCRIPTION
**Pull request by Khan8615**
Over Rides Default Behavior for setting the player's threat level

Renamed for a more accurate description of what it actually does.

### CODE REVIEW

**Comment by Retributive-Law** [comment]
Unsubscribe

**Comment by Khan8615** [comment]
This is needed to override the amount of clothing the player wears for when the helicopter targets them. By having this hook I can set my own levels. 

This cannot be achieved in the existing CanHelicopterTarget Hook.

**Comment by Khan8615** [comment]
`        private object OnPlayerEnsureUpdated(BasePlayer player)
        {
            if (player.inventory.containerWear.itemList.Count >= _settings.MaxClothingCount)
            {
                player.cachedThreatLevel += 2f;
            }

            foreach (Item item in player.inventory.containerBelt.itemList)
            {
                BaseEntity heldEntity = item.GetHeldEntity();
                if (!_settings.RestrictedWeapons.Contains(item.info.shortname)) continue;
                if (heldEntity == null || !(heldEntity is BaseProjectile) || heldEntity is BowWeapon) continue;
                player.cachedThreatLevel += 2f;
                break;
            }

            return true;
        }`

**Comment by lukespragg** [comment]
Added with name change per team discussion. Thanks!
- object OnThreatLevelUpdate(BasePlayer player)

**Pull request closed without merging**
