### PR TITLE
Add helper classes for Cui to improve ease of use

### PR DESCRIPTION
**Pull request by thibmo**

### CODE REVIEW

**Comment by thibmo** [comment]
Need to still improve argument positions and add the "name" argument.
Any feedback is welcome while I wait for time to fix those points. :)

**Comment by lukespragg** [comment]
It looked alright to me for the most part, thought some of those methods have some undesirable formatting. I believe @Mughisi has some feedback for you, though I'm not sure when he'll be able to give that.

**Comment by thibmo** [comment]
That's fine, wasn't too happy with them just yet either.
Any feedback is welcome. :)

**Comment by thibmo** [comment]
Closing PR to make space for updated PR (With repo that's up-to-date with current development branch)

**Pull request closed without merging**
