### PR TITLE
I lose compiler.exe when i use latest version.

### PR DESCRIPTION
**Pull request by zzy0217gg**
I lose compiler.exe when i use latest version.(v2.0.4428)

### CODE REVIEW

**Comment by zzy0217gg** [comment]
@lukespragg I lose compiler.exe when i use latest version.(v2.0.4428)

**Comment by zzy0217gg** [comment]
Can you send the solution to my email  (317527976@qq.com)

**Comment by lukespragg** [comment]
Please use our forums for support. There have been no changes to how the compiler is downloaded or handled though.

**Comment by zzy0217gg** [comment]
@lukespragg

**Comment by zzy0217gg** [comment]
in china has wall

**Comment by zzy0217gg** [comment]
image

**Comment by zzy0217gg** [comment]
Missing shader in Main Camera (TOD_Scattering)
Missing shader in Main Camera (TOD_Scattering)
Missing shader in Main Camera (TOD_Scattering)
Missing shader in Main Camera (TOD_Rays)
Missing shader in Main Camera (TOD_Rays)
Missing shader in Main Camera (TOD_Rays)
Missing shader in effect - Screen Blur (UnityStandardAssets.ImageEffects.BlurOptimized)
Missing shader in effect - Cold (ScreenOverlayEx)
Missing shader in effect - Screen Blur (UnityStandardAssets.ImageEffects.ColorCorrectionCurves)
Missing shader in effect - Screen Blur (UnityStandardAssets.ImageEffects.ColorCorrectionCurves)
Missing shader in effect - Screen Blur (UnityStandardAssets.ImageEffects.ColorCorrectionCurves)
Missing shader in effect - Hurt (UnityStandardAssets.ImageEffects.VignetteAndChromaticAberration)
Missing shader in effect - Hurt (UnityStandardAssets.ImageEffects.VignetteAndChromaticAberration)
Missing shader in effect - Hurt (UnityStandardAssets.ImageEffects.VignetteAndChromaticAberration)
Missing shader in effect - Radiation (UnityStandardAssets.ImageEffects.ColorCorrectionCurves)
Missing shader in effect - Radiation (UnityStandardAssets.ImageEffects.ColorCorrectionCurves)
Missing shader in effect - Radiation (UnityStandardAssets.ImageEffects.ColorCorrectionCurves)
Missing shader in effect - Radiation (UnityStandardAssets.ImageEffects.NoiseAndGrain)
Missing shader in effect - Hurt (ScreenOverlayEx)
Missing shader in effect - Hot (UnityStandardAssets.ImageEffects.VignetteAndChromaticAberration)
Missing shader in effect - Hot (UnityStandardAssets.ImageEffects.VignetteAndChromaticAberration)
Missing shader in effect - Hot (UnityStandardAssets.ImageEffects.VignetteAndChromaticAberration)
Missing shader in effect - FXAA (FXAA)
Missing shader in effect - Water (UnityStandardAssets.ImageEffects.BlurOptimized)
Loading Oxide Core v2.0.3972...
Loading extensions...
Loaded extension CSharp v2.0.4010 by Oxide and Contributors
Loaded extension MySql v2.0.3755 by Oxide and Contributors
Loaded extension Rust v2.0.4428 by Oxide and Contributors
Loaded extension SQLite v2.0.3754 by Oxide and Contributors
Loaded extension Unity v2.0.3768 by Oxide and Contributors
Could not check for update to Compiler.exe
Error: ConnectFailure (鐢变簬杩炴帴鏂瑰湪涓€娈垫椂闂村悗娌℃湁姝ｇ‘绛斿鎴栬繛鎺ョ殑涓绘満娌℃湁鍙嶅簲锛岃繛鎺ュ皾璇 曞け璐ャ€?
)

Using Covalence provider for game 'Rust'
Loading plugins...
Loaded plugin Rust v2.0.4428 by Oxide and Contributors
Loaded plugin Unity v2.0.3768 by Oxide and Contributors
Could not check for update to Compiler.exe
Error: ConnectFailure (鐢变簬杩炴帴鏂瑰湪涓€娈垫椂闂村悗娌℃湁姝ｇ‘绛斿鎴栬繛鎺ョ殑涓绘満娌℃湁鍙嶅簲锛岃繛鎺ュ皾璇 曞け璐ャ€?
)

Exception while starting compiler version Unknown:  (Win32Exception: ApplicationName='E:\rust\Compiler.exe', CommandLine='/service /logPath:E:\rust\oxide\logs', CurrentDirectory='', Native error= 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?
)
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x002dc] in <0079a30f96a047348857e1cecc6c638a>:0
  at System.Diagnostics.Process.Start () [0x0003a] in <0079a30f96a047348857e1cecc6c638a>:0
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at Oxide.Plugins.PluginCompiler.CheckCompiler () [0x001f3] in <efb9a8684e344ecfa065c7b416e6d2fd>:0

Win32 NativeErrorCode: 2 ErrorCode: -2147467259 HelpLink:
Error while compiling: compiler version Unknown couldn't be started
Loading Prefab Bundle 0%
Loading Prefab Bundle 0%

**Comment by lukespragg** [comment]
https://umod-01.nyc3.digitaloceanspaces.com/Compiler.exe

**Comment by zzy0217gg** [comment]
china has wall,but thank for you understand




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Luke Spragg"<notifications@github.com&gt;; 
发送时间: 2020年2月2日(星期天) 凌晨2:15
收件人: "OxideMod/Oxide.Rust"<Oxide.Rust@noreply.github.com&gt;; 
抄送: "安稳张志远"<zzy0217gg@vip.qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OxideMod/Oxide.Rust] I lose compiler.exe when i use latest version. (#186)




https://umod-01.nyc3.digitaloceanspaces.com/Compiler.exe
 
&mdash;

**Pull request closed without merging**
