### PR TITLE
Add OnPlayerReport

### PR DESCRIPTION
**Pull request by SolidSnake-72**
Add OnPlayerReport pre-hook to allow cancelling

### CODE REVIEW

**Comment by lukespragg** [comment]
What would be the purpose of this hook? Like, when would this be necessary?

**Comment by SolidSnake-72** [comment]
To either allow or block the sending of player reports, based on player. Currently there is no way to do this for players who abuse the report system. I also see a lot of players sending reports based on server-specific rule violations, not realizing this goes to Facepunch/EAC for game ban consideration.

**Comment by lukespragg** [comment]
So one thought was to hook the 'cheatreport' ConVar instead of the other method to avoid the extra DLL being patched, which would probably be fine given that's the only place I see that calls that method right now. Thoughts?

**Comment by soulfly006** [comment]
They want to intercept and cancel the report…which is not what facepunch wants

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by SolidSnake-72** [comment]
I did try to hook the ConVar initially, but unfortunately that only works for cheat reports, not abuse or spam.

**Comment by lukespragg** [comment]
Based on what others have suggested, it sounds like this wouldn't have any benefit being as the client sends directly to Facepunch.

**Pull request closed without merging**
