### PR TITLE
Added 5 fishing hooks.

### PR DESCRIPTION
**Pull request by ThePitereq**
Added 4 hooks to BaseFishingRod and 1 for WildlifeTrap.

object CanCastFishingRod(BasePlayer player, BaseFishingRod fishingrod, Item lure) - Called before player fishing rod cast.
void OnFishingRodCast(BasePlayer player, BaseFishingRod fishingrod, Item lure) - Called after player fishing rod cast.
object OnFishCaught(BasePlayer player, BaseFishingRod fishingrod, Item fish) - Called when player catch a fish.
void OnFishingInterrupted(BaseFishingRod fishingrod, BaseFishingRod.FailReason reason) - Called at fishing interrupted by fail.
object CanWildlifeTrap(WildlifeTrap trap, TrappableWildlife trapped) - Called when fish is caught to the fish trap.

Sorry for so much pull requests. I am still learning how to use Git :)

### CODE REVIEW

**Comment by lukespragg** [comment]
Haven't forgotten about you! There are a couple issues we're discussing regarding this, but there'll likely need to be a few changes with return handling and naming, as well as some additional post hooks where they make sense.

**Comment by ThePitereq** [comment]
Hey. I set the names according to the docs. If something is wrong, then sorry. All hooks worked for me in the way as I wanted. It's not mentioned there, but OnFishCaught can return fish that is caught. I've not made any more additional hooks, because i though that is enough, and I didn't have any idea for implementing more :)

**Comment by lukespragg** [comment]
This is what we ended up with, let me know if anything doesn't make sense!

- bool CanCastFishingRod(BasePlayer player, BaseFishingRod fishingRod)
- bool CanCatchFish(BasePlayer player, BaseFishingRod fishingRod, Item fish)
- object OnWildlifeTrap(WildlifeTrap trap, TrappableWildlife trapped)
- void OnFishCaught(Item fish, BaseFishingRod fishingRod, BasePlayer player)
- void OnFishingRodCast(BaseFishingRod fishingRod, BasePlayer player)
- void OnFishingStopped(BaseFishingRod fishingRod, BaseFishingRod.FailReason reason)

**Comment by ThePitereq** [comment]
I see that you've removed lure variable. Maybe I am blind but i didn't see any available way to get the item that has been used as lure (I am not talking about fishing rod inventory) on fishing rod cast. Besides, everything seems to be correct. Thank you! :)

**Comment by lukespragg** [comment]
Likely just missed it! I'll take a look.

**Comment by ThePitereq** [comment]
I think it is possible, to check inventory at CanCastFishingRod and then save value and go to OnFishCaught, but i think adding it will be better. ^^

**Pull request closed without merging**
