### PR TITLE
Expose BuildingBlock.DoRotation as public

### PR DESCRIPTION
**Pull request by ChristianLW**

### CODE REVIEW

**Comment by lukespragg** [comment]
Merged in with a few others, thanks!

**Comment by ChristianLW** [comment]
I don't want to seem pushy, but I noticed this hasn't been merged/commited to the repo yet.
I just want to make sure it hasn't been dropped or overlooked.
Is it possible to give an update on the status of this PR?
@lukespragg

**Comment by lukespragg** [comment]
Pretty sure it was, but I’ll check to make sure it was.

**Comment by lukespragg** [comment]
All good now, good catch!

**Pull request closed without merging**
