### PR TITLE
Update Rust.opj add OnPlayerDisconnected

### PR DESCRIPTION
**Pull request by XAuBAH**
please could you add OnPlayerDisconnected to
ServerMgr.ReadDisconnectReason(Message packet)
this disconnections is not caching now

### CODE REVIEW

**Comment by lukespragg** [comment]
We'll take a look.

**Comment by XAuBAH** [comment]
please!
it will be catch disconnections like this
`[10:22:41] 91.219.138.209:60889/7656119834927***/Klikastik disconnecting: Exception (cs:57814): JsonReaderException: Unexpected character encountered while parsing value:  . Path '', line 0, position 0. Newtonsoft.Json.JsonTextReader.ParseValue () (at <00000000000000000000000000000000>:0) Newtonsoft.Json.JsonTextReader.Read () (at <00000000000000000000000000000000>:0) Newtonsoft.Json.JsonReader.ReadAndMoveToContent () (at <00000000000000000000000000000000>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <00000000000000000000000000000000>:0) Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <00000000000000000000000000000000>:0) Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at <00000000000000000000000000000000>:0) Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at <00000000000000000000000000000000>:0) Rust.Workshop.Skin.DeserializeManifest () (at <00000000000000000000000000000000>:0) System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)  
`

or like this
`[19:02:22] 2.135.121.59:51312/7656119907*****/KoT disconnecting: Exception (cs:57814): ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.  Parameter name: index System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <00000000000000000000000000000000>:0) System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <00000000000000000000000000000000>:0) SoundManager.RequestSoundInstance (SoundDefinition def, UnityEngine.GameObject targetParent, UnityEngine.Vector3 position, System.Boolean firstPerson) (at <00000000000000000000000000000000>:0) SoundPlayer.CreateSound () (at <00000000000000000000000000000000>:0) SoundPlayer.MakeThirdPerson () (at <00000000000000000000000000000000>:0) EffectLibrary.SetupEffect (UnityEngine.GameObject go, Effect effect) (at <00000000000000000000000000000000>:0) EffectLibrary.CreateEffect (System.String strPrefab, Effect effect) (at <00000000000000000000000000000000>:0) BaseProjectile.OnSignal (BaseEntity+Signal signal, System.String arg) (at <00000000000000000000000000000000>:0) BaseEntity.OnRpcMessage (BasePlayer player, System.UInt32 rpc, Network.Message msg) (at <00000000000000000000000000000000>:0) HeldEntity.OnRpcMessage (BasePlayer player, System.UInt32 rpc, Network.Message msg) (at <00000000000000000000000000000000>:0) BaseProjectile.OnRpcMessage (BasePlayer player, System.UInt32 rpc, Network.Message msg) (at <00000000000000000000000000000000>:0) BaseEntity.CL_RPCMessage (System.UInt32 nameID, System.UInt64 sourceConnection, Network.Message message) (at <00000000000000000000000000000000>:0) Client.OnRPCMessage (Network.Message packet) (at <00000000000000000000000000000000>:0) Client.OnNetworkMessage (Network.Message packet) (at <00000000000000000000000000000000>:0) Facepunch.Network.Raknet.Client.HandleMessage () (at <00000000000000000000000000000000>:0) Facepunch.Network.Raknet.Client.Cycle () (at <00000000000000000000000000000000>:0) Client.Update () (at <00000000000000000000000000000000>:0) UnityEngine.Debug 
`

**Comment by XAuBAH** [comment]
this disconnections are now shows only in console

**Comment by XAuBAH** [comment]
> We'll take a look.

So what do you think?

**Pull request closed without merging**
