### PR TITLE
Add hook OnClientDisconnectReason

### PR DESCRIPTION
**Pull request by rostov114**
Executing hook on disconnect player with reason.

```csharp
void OnClientDisconnectReason(Network.Connection connection, string reason)
```

### CODE REVIEW

**Comment by rostov114** [comment]
This hook has been requested in PR #279

**Comment by lukespragg** [comment]
Does the existing OnClientDisconnect hook not catch this already?

**Comment by rostov114** [comment]
No.

OnClientDisconnect - runs at the level of the Network library. In it, you can track when a person flew out on Time Out.
OnClientDisconnectReason - processes the `Message.Type.DisconnectReason` packet from the client.

They complement each other.

**Comment by lukespragg** [comment]
Would it make sense to have them both named the same then?

**Comment by rostov114** [comment]
I named it from the logic that it is the client / connection that is disconnected.
But I will not mind if you rename it.

**Comment by lukespragg** [comment]
Right, I was going to rename the other to OnClientDisconnected and have this one as OnClientDisconnected as well.

**Comment by rostov114** [comment]
Probably more correct this way:

OnClientDisconnect(Connection, string) -> OnClientDisconnected(Connection, string)   ( since it is executed last )
OnClientDisconnectReason(Connection, string) -> OnClientDisconnect(Connection, string)

**Comment by lukespragg** [comment]
Thanks, merged with the suggestions.

**Pull request closed without merging**
