### PR TITLE
Added hook "OnNoteUpdate" to keep track of changes or prevent them

### PR DESCRIPTION
**Pull request by 21mac**
Needed the possibility to prevent changes to notes for a plugin I am working on.

### CODE REVIEW

**Comment by KrunghCrow** [comment]
can already block that look at my StationaryPaper plugin

**Comment by 21mac** [comment]
> can already block that look at my StationaryPaper plugin

I did, but I did not see any oxide hook. You use a method called "OnNoteEdit" which is not a hook and therefore does not get called by oxide when a note is changed. You call that function by a console command.
How can this prevent the change by a user?

**Comment by Substrata1** [comment]
Here is an example of how you can do this:
```csharp
object OnServerCommand(ConsoleSystem.Arg arg)
{
    if (arg?.cmd?.FullName == "note.update")
    {
        BasePlayer player = arg.Player();
        string itemid = arg.GetString(0, "");
        string text = arg.GetString(1, "");

        if (text.Contains("bannedword"))
        {
            return true;
        }
    }

    return null;
}
```

**Comment by MrBlue** [comment]
This can be achieved using the OnServerCommand hook as shown above, thanks for your contribution though!

**Comment by 21mac** [comment]
Finally tried it.

Works fine, thanks a lot :)

**Pull request closed without merging**
