### PR TITLE
Added CanHit hook 

### PR DESCRIPTION
**Pull request by Wolfleader101**
Added CanHit hook to allow modifications to what hammers can hit

### CODE REVIEW

**Comment by rostov114** [comment]
CanHit is client side method. In server is not using.

**Comment by rostov114** [comment]
Method found in

image

Found 1 match in BaseMelee
image

Method not calling in server.

-----

Client (version 2183)

Found 2 match in BaseMelee
image

**Comment by rostov114** [comment]
@lukespragg can close PR?
Hook not work.

**Comment by Wolfleader101** [comment]
well yes its not working bc the patch screwed it up a little 🤣  i will fix it later. tried last night when free and it didnt work

**Comment by Slut** [comment]
Hook will work correctly, it would just need to be hooked in the override (Hammer).

Make a clean server install (ensure you're on the right branch and fully updated), install oxide then update server again to remove patched files then load the latest opj from github and make your changes.

One thing I would recommend (but not entirely sure) is to remove all the "_Original" files

**Comment by Wolfleader101** [comment]
> Hook will work correctly, it would just need to be hooked in the override (Hammer).
> 
> Make a clean server install (ensure you're on the right branch and fully updated), install oxide then update server again to remove patched files then load the latest opj from github and make your changes.
> 
> One thing I would recommend (but not entirely sure) is to remove all the "_Original" files

ok thanks

**Comment by Wolfleader101** [comment]
followed @Slut and it still is changing lots of lines in opj file

**Pull request closed without merging**
