### PR TITLE
Moved OnGrowableGathered to earlier index

### PR DESCRIPTION
**Pull request by Vlad-00003**
This would help those who want to change the item BEFORE it was giving to the player.
Example: changing amount.

If we would change amount after the item was given - the player would receive notification that he get original amount, as amount was changed after it was given.

This way - if we would change amount - the notification would show correct value, so we won't have to make another with the difference.

### CODE REVIEW

**Comment by lukespragg** [comment]
Not ideal, but understandable.

**Comment by Vlad-00003** [comment]
So you would leave it as it is now?

**Comment by Vlad-00003** [comment]
This also makes this hook inconsistent with overs, like OnDispenserGather

**Comment by Vlad-00003** [comment]
Oh, right, I see. 00cfb4310e4a342d25f17fa6f603387dc9f9a9ff

Thanks :3

**Pull request closed without merging**
